name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOCKER_USERNAME: winniemonel
  POSTGRES_PORT: 5432
  POSTGRES_HOST: localhost
  POSTGRES_USER: winniemonel
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: consulting
  POSTGRES_DB_CHARSET: utf8
  SPRING_JPA_HIBERNATE_DDL_AUTO: update

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ env.SPRING_JPA_HIBERNATE_DDL_AUTO }}
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 19 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '19'
          overwrite-settings: false
      - name: Build with Maven
        run: mvn package -B
        continue-on-error: true
        id: build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=WinnieParton_jeudecartes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: success()